moved src to correct location

diff --git a/OpenMowerOS/src/modules/comitup/start_chroot_script b/OpenMowerOS/src/modules/comitup/start_chroot_script
--- a/OpenMowerOS/src/modules/comitup/start_chroot_script
+++ b/OpenMowerOS/src/modules/comitup/start_chroot_script
@@ -1,34 +1,54 @@
 #!/usr/bin/env bash
-# Comitup
-# This installs comitup into the CustomPiOS
-# Written by Clemens Elflein
+# CustomPiOS module : comitup
+# <Description what this module does>
+# Written by DocGalaxyBlock (https://github.com/docgalaxyblock/)
 # GPL V3
 ########
 
-
 # Source error handling, leave this in place
-set -x
-set -e
+set -ex
 
+# Source CustomPIOS common.sh
 source /common.sh
 install_cleanup_trap
 
+# ToDo Ubuntu check https://github.com/davesteele/comitup/issues/209#issuecomment-1209916831
+#
+# disabling systemd-resolveds caching DNS stub resolver on ubuntu
+# https://github.com/pi-hole/docker-pi-hole/#installing-on-ubuntu
+##
+#if [ "${BASE_DISTRO}" == "ubuntu" ] ; then
+#    sed -r -i.orig 's/#?DNSStubListener=yes/DNSStubListener=no/g' /etc/systemd/resolved.conf
+#    sh -c 'rm /etc/resolv.conf && ln -s /run/systemd/resolve/resolv.conf /etc/resolv.conf'
+#fi
 
-# Install comitup copy pasted from tutorial
-# https://github.com/davesteele/comitup/wiki/Installing-Comitup
+echo_green "Installing comitup..."
 wget https://davesteele.github.io/comitup/latest/davesteele-comitup-apt-source_latest.deb
 dpkg -i --force-all davesteele-comitup-apt-source_latest.deb
 rm davesteele-comitup-apt-source_latest.deb
-apt-get update
-apt-get install -y --no-install-recommends comitup comitup-watch
-rm /etc/network/interfaces
-systemctl mask dnsmasq.service
-systemctl mask systemd-resolved.service
-systemctl mask dhcpd.service
-systemctl mask dhcpcd.service
-systemctl mask wpa-supplicant.service
-systemctl enable NetworkManager.service
+apt-get update --allow-releaseinfo-change
+apt-get install --yes comitup --no-install-recommends
 
-# Echo the defaults into the comitup config file
-echo "ap_name: $COMITUP_NAME" >> /etc/comitup.conf
-echo "ap_password: $COMITUP_PASSWORD" >> /etc/comitup.conf
+# enable required services and mask conflicting services
+systemctl enable NetworkManager.service
+systemctl_if_exists mask dhcpd.service
+systemctl_if_exists mask dhcpcd.service
+systemctl_if_exists mask wpa-supplicant.service
+systemctl_if_exists mask raspberrypi-net-mods.service
+
+# copy the stock config to an example
+cp /etc/comitup.conf /etc/comitup.conf.example
+
+# this service checks if a comitup.conf exist on the boot partition of the sd card
+# if so it copys it to /etc/comitup.conf and renames the one in boot to comitup.conf.settings-applied
+if [ "$COMITUP_COPY_SERVICE" == "yes" ]; then
+    echo_green "Installing comitup user config copy service..."
+    unpack /filesystem/etc /etc
+    systemctl enable comitup_config_copy.service
+fi
+
+
+
+#cleanup
+apt-get clean
+apt-get autoremove --yes
diff --git a/OpenMowerOS/src/modules/openocd/start_chroot_script b/OpenMowerOS/src/modules/openocd/start_chroot_script
--- a/OpenMowerOS/src/modules/openocd/start_chroot_script
+++ b/OpenMowerOS/src/modules/openocd/start_chroot_script
@@ -1,25 +1,31 @@
 #!/usr/bin/env bash
-# OpenOCD module
-# Installs OpenOCD with RP2040 and Pi4 GPIO support
+# CustomPiOS OpenOCD module
 # Written by Clemens Elflein
 # GPL V3
 ########
 
-
 # Source error handling, leave this in place
-set -x
-set -e
+set -ex
 
 source /common.sh
 install_cleanup_trap
 
-echo "Installing OpenOCD (RP2040 version with Pi4 GPIOs)"
-apt install -y --no-install-recommends git automake autoconf build-essential libtool libftdi-dev libusb-1.0-0-dev texinfo pkg-config rpi.gpio-common
+echo "Installing OpenOCD dependencys"
+apt-get update --allow-releaseinfo-change
+apt-get install --yes --no-install-recommends git autoconf automake build-essential pkg-config texinfo libtool libftdi-dev libusb-1.0-0-dev rpi.gpio-common
+
+echo "Installing OpenOCD"
 git clone https://github.com/raspberrypi/openocd.git --recursive --branch rp2040 --depth=1
 cd openocd
 ./bootstrap
 ./configure --enable-ftdi --enable-sysfsgpio --enable-bcm2835gpio
 make -j$(nproc)
-sudo make install
+make install
 cd ..
 rm -rf openocd
+
+
+
+#cleanup
+apt-get clean
+apt-get autoremove --yes
